# Generated by Django 5.2.4 on 2025-07-28 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='childimage',
            old_name='uploded_at',
            new_name='uploaded_at',
        ),
    ]
